name: Deploy Website

on:
  push:
    branches:
      - main # Mude para master se sua branch principal se chamar master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Gerar o Build com Vite
        run: npm run build

      - name: Deploy para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta correta gerada pelo seu Vite
          branch: gh-pages
